### ISSUE TITLE
Get page source with quine hacks

### ISSUE THREAD

**Issue by HiyoriShiina** [gildas-lormeau/SingleFileZ#111]
If I understand it correctly, the script needs to fetch the source of the web page, i.e. the zip file, to decode the content. But fetching the web page again isn't available in every protocol, which causes issue #105. IMO using [quines](https://en.wikipedia.org/wiki/Quine_(computing)) serves this purpose in a more robust approach.

I have a working prototype of quine but I can't reproduce the exact binary data in the CDATA section. Ideally I would want to fetch the data in CDATA using DOM API, but according to some StackOverflow answers, the browsers always try to decode the raw string. (Even storing binary data in CDATA section is not supported in the standard, but I get that it's a compromise.)

Currently, I have two proposals:

1. Store the zip data in the JS as well. The problem is that it has 2x file size + overhead (e.g. Base64) but can be solved with an option to turn it off.
2. Find a way somehow to correctly restore the data in the CDATA section.

Let me know what you think!

---
## Disclaimer
I have a project with the exact same purpose. It was a headache that zip files can't be opened directly in the browser and MHTML files aren't supported everywhere & scripts are banned. I found your idea of self-extractable HTML really awesome and it blew my mind when I saw it yesterday.

My implementation added some features tailored to my needs, e.g. source links, lazy-loading for specific sites, etc. The repo is not public due to personal reasons, but I would be happy to invite you to have a look at it. It is not feature-complete so I'll probably just merge my code over here.

Thanks again for the great work!

**Comment by gildas-lormeau** [comment]
First of all, I'm glad SingleFilZ blew your mind, that was my main motivation when I designed it :). 

If I follow you well, you propose to store the content of the zip in a JavaScript string rather than in a CDATA section. This approach would be really interesting if it was possible to store a binary content, as is, in a string. Unfortunately this is not possible because some characters are forbidden if they are not escaped. For example `"` or `'` can cause problems. 
So, it is indeed possible to encode the binary content in base64 (in a JavaScript string or in the HTML content as a CDATA section) but, in my opinion, this takes away the whole advantage of SingleFileZ. I am very attached to the fact that a file can be unzipped, it is for me the most important feature.

Note that the bug that prevents SingleFileZ from working because of Manifest V3 is specific to Chromium. It seems that Google may consider fixing it, see https://crbug.com/1051597#c9. At this time, I'm still waiting to see what this bug report will become.

**Comment by HiyoriShiina** [comment]
Thanks for your reply and your detailed explanation! I'm glad I got that right :-)

Just to clarify that I proposed to store the binary content in Base64 together with the existing binary CDATA section. That would not prevent the file from being able to be unzipped. This could be a potential workaround at the time being.

Do you think that there is any approach to fetch the binary content stored in the CDATA section using JS without re-fetching the page? Or is there some other ways to store the binary content in a HTML file?

**Comment by gildas-lormeau** [comment]
Thank you for the clarification, I didn't understand that you wanted to store the binary content both in JS encoded in base64 and in binary in the CDATA section. I confirm this solution can work but I'm not very motivated to implement it right now because I don't want Google to close the bug assuming that a workaround has been found. This kind of situation has already happened to me in the past when they decided content scripts would not be able to fetch the page in binary (see https://crbug.com/1049604).

I did a lot of tests but I wasn't able to retrieve the content of the CDATA section without fetching it. Actually, the content of the section altered by the HTML parser because the binary content is not valid. The approach I tried was to change the encoding of the page but, in all cases, some bytes were always altered. As far as I know, HTML does not allow binary content (but the parser is tolerant to faults), that's why data URIs were invented.

**Comment by HiyoriShiina** [comment]
I understand your motivation now. If that's the case, it seems better not to use the workaround even I have a working implementation.

It is unfortunate to hear that your attempts on CDATA failed as well. I can live with using a web server to serve the page where the extension is not available. In the worst case, it's still a valid ZIP.

Thank you for your kind tips! Closing as I have no further proposals.

**Comment by gildas-lormeau** [comment]
@HiyoriShiina FYI, Google is actually implementing the support of file URI when using fetch in an extension, see https://chromium-review.googlesource.com/c/chromium/src/+/3179883/

So, there's some hope SingleFileZ will work with MV3.

**Comment by HiyoriShiina** [comment]
Thanks for your notice! I'll be sure to keep myself updated.

**Comment by eyaler** [comment]
@gildas-lormeau @HiyoriShiina Hey guys, very interesting discussion. I guess I am a little late to the game, but I just discovered the awesomeness of SingleFileZ! My framework [ZTML](https://github.com/eyaler/ztml) is a self extracting js/html for compression of large inline texts, but can also be used for complete websites (and i combine it with my [WEBZOS](https://wbtz.github.io) framework for archiving single page rich media websites on the blockchain... for which your single file saving functionality is very useful). Anyway, to solve the inline binary data issue, I either use my base125 variation of the aforementioned base122, or better, my crEnc variation of yEncode. the latter uses single byte encoding CP1252 and has a overhead of only 1.2%. The payload is saved in JS template literals with minimal escaping, and I take care of the browsers automatic [character substitution](https://html.spec.whatwg.org/multipage/parsing.html#table-charref-overrides), you've mentioned. I wonder if you could use something like that and still get a valid ZIP file. Would be happy to colab on this!

**Comment by gildas-lormeau** [comment]
@eyaler Thank you for the kind words and the suggestion! Your proposal is interesting, I will try to code a PoC to see what it would look like. Normally, it shouldn't be too complicated.

**Comment by gildas-lormeau** [comment]
I fixed the original issue in the last version (1.4.x). Now, with the default settings, page saved with SingleFileZ can be opened in any "modern" browser (supporting JS), just like SingleFile. This is achieved by consolidating altered data read from the DOM. This consolidation makes the file about approx. 1% larger.
