### ISSUE TITLE
This page cannot be saved with SingleFileZ

### ISSUE THREAD

**Issue by badbrad1m** [gildas-lormeau/SingleFileZ#143]
I use SingleFileZ every day - consistently on one website (Barchart.com) and perhaps a few other websites each day.  A week ago, I began to get the error message, "This page cannot be saved with SingleFileZ".  The Firefox extension will not not save anything from any site.  SingleFile works, but SingleFileZ does not.  I've tried disabling other extensions and re-starting Firefox (95.0.2 64 bit) - none of which fix the problem.  What would now be causing this problem, and what can I try, to troubleshoot?  Thanks!

**Comment by gildas-lormeau** [comment]
This bug is really weird because it is exactly the same code that is executed in both extensions to detect if the page can be saved. From a technical point of view this message is displayed if the background script of the extension has not been able to join the content script injected in the tab. This message is typically displayed if you try to save internal pages like the reader view (because they don't support extensions) or a page on the the Mozilla store.
The only thing I can think of is a corrupted profile problem. Try testing with a new profile in Firefox.
