### ISSUE TITLE
Possible to combine/reference multiple pages? 

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFileZ#20]
This issue was initially opened for SingleFile, cf. https://github.com/gildas-lormeau/SingleFile/issues/106.

I think this job would be more appropriate for SingleFileZ.

**Comment by boweden** [comment]
Revisiting this old topic here as I think this is an essential feature that SingleFileZ should still pursue.  I'm currently using a different tool (wget) for this problem because it provides a working solution, but I truly believe SingleFileZ can also do this.


For example, let's say we want to save this webpage:

https://gamefaqs.gamespot.com/pc/564462-a-mind-forever-voyaging/faqs/74934

This page has multiple webpages (page=0, page=1 and page=2) referenced within the main HTML.  If we try to save this page with SingleFileZ, currently it would only save the first page (page=0), and the links to page=1 and page=2 would be non-local (i.e. the references to page=1 and page=2 inside page=0 would be online absolute paths, not local relative paths).  Okay, nothing new, just stating the obvious.

Now, let's see how wget solves this problem.  I should admit I've only just started using wget recently so I don't know if these are the "best" options to pass along to wget.

wget --mirror --convert-links --adjust-extension --page-requisites --no-parent --user-agent="Googlebot/2.1 (+https://www.googlebot.com/bot.html)" https://gamefaqs.gamespot.com/pc/564462-a-mind-forever-voyaging/faqs/74934


wget would then make a copy of page=0, page=1, and page=2 separately and a fourth "main" page (which also happens to be the same as page=0) that keeps everything together via relative paths.  I would then create a Shortcut (or a Symbolic link) to this "main" page to browse this site locally.

I should note that this method would only work on webpages where the references to other pages are on the same level or in subdirectories, not to parent folders or different branches outside current directory (obviously we don't want endless recursion).

So my question is, would it be possible for SingleFileZ to emulate this behavior of wget?  It's not perfect, but still it's better than nothing?

**Comment by gildas-lormeau** [comment]
SingleFile can now crawl websites. This might interest you, cf. https://github.com/gildas-lormeau/SingleFile/issues/371. However, it does not rewrite links.

**Comment by boweden** [comment]
oh, wow. Sorry, I didn't know that. Should've RTFM. 

That's very cool if it can already do all this.  I will try out that feature soon. :)

Thank you again for this wonderful tool.

**Comment by gildas-lormeau** [comment]
No problem ;). Coincidentally, I just added these new features.

**Comment by gildas-lormeau** [comment]
I close this issue because wget should do the job.
