### ISSUE TITLE
In the saved pages hidden elements don't removed!

### ISSUE THREAD

**Issue by vzcoder** [gildas-lormeau/SingleFileZ#32]
Please check the operation of this option.
I can attach the last file I saved.
I decided to open it and see why it was so huge.
Since visually, on the saved page, I see not so much information.

Sometimes, when viewing some pages, it is proposed the so-called reading mode, a simplified mode. In it, the page is reformatted and simplified.
Can this feature be added to your extension? (Can be added to your extension is the opportunity?)
This would be very good, because it is very much needs to reduce the size of the stored files !!!

I use uBlock Origin to hide items I don't need because I don't even know if there's a replacement for it.

**Comment by gildas-lormeau** [comment]
You can save the page as it would be viewed in reader mode by using a userscript as described here: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved and using this userscript https://gist.github.com/gildas-lormeau/963f363bce2a7bdb53b46ec74e11bf5c. In this script, you'll have to replace all the occurrences of `single-file-` with `single-filez-` to use it with SingleFileZ instead of SingleFile.

Regarding the unexpected huge page, posting the URL here would suffice in order to see what's wrong.

**Comment by vzcoder** [comment]
Thank you for your quick response !!!

https://cloud.mail.ru/public/3Ud7/4AqXiYvfr
https://cloud.mail.ru/public/bGkY/51ccKYC6L
These are the files where I saw the effect of not removing hidden elements
Это те файлы на которых я увидел эффект не удаления скрытых элементов

https://cloud.mail.ru/public/4ETm/3yCviKRzj  -  This is my setting - singlefilez-settings.json

**Comment by gildas-lormeau** [comment]
Sorry for the very late response, I forgot to check this issue. By looking at the source code, it looks like this is the same issue than https://github.com/gildas-lormeau/SingleFile/issues/312. I'll try to see what I can do do make the page smaller.

**Comment by gildas-lormeau** [comment]
I implemented a way to improve the removal of unused fonts on the examples you provided in the version 0.5.3 I just published. Thus, pages will be a bit smaller when saving selected contents on Youtube. There is still room for improvements though.
