### ISSUE TITLE
Opening saved page fails with Firefox but displays okay if manually unzipped

### ISSUE THREAD

**Issue by JBigglesworth** [gildas-lormeau/SingleFileZ#34]
Using SingleFileZ 0.4.7 on Firefox 72.0.2 x64 (Win 10 Pro x64 1909 Build 18363.592) I'm finding some save pages fail to open. I can manually unzip them then they'll open okay. (ie: double clicking on extracted index.html results in Firefox opening and correctly displaying the page).

I have been able to open a (failing) saved page by selecting to open it in the Edge browser.

Given my Firefox has SingleFileZ installed, is there some code in SingleFileZ that may be causing this decompression error to occur when Firefox is invoked to open the save page - or is it a Firefox bug?

The attached is a zip of a page that's failing to open automatically. (ie: zipped html/zip file!)

[2020-01-22  PRIME B450M-A.zip](https://github.com/gildas-lormeau/SingleFileZ/files/4137600/2020-01-22.PRIME.B450M-A.zip)

**Comment by gildas-lormeau** [comment]
Thank you for having submitted this issue. It was due to the fact that you disabled the option "remove scripts". Unfortunately, it's impossible for SingleFile to guarantee that you'll get the expected result when this option is disabled. 
However, I was able to circumvent the issue in the page you gave as example. Saving it with the version 0.4.8 (that I just published) should fix it. If you don't need scripts, I highly recommend you to let enabled the option "remove scripts".

**Comment by JBigglesworth** [comment]
Thanks for the change re 0.4.8, it did the job!

The reason I'd taken to disabling the 'remove scripts' option was that I'd found I couldn't switch tabs in tables on some saved pages. - Perhaps I should have queried whether this is a SingleFileZ bug?

**Comment by gildas-lormeau** [comment]
Your use of the option is legitimate. When you have a similar issue with saved pages and the option is disabled, try to save them with the option enabled first. If the issue persists, feel free to file a new issue here and I'll do my best to fix it.
