### ISSUE TITLE
Unable to replicate pages with "spoiler" text

### ISSUE THREAD

**Issue by boweden** [gildas-lormeau/SingleFileZ#48]
Hello again, 

I'm trying to save this page:  

https://intfiction.org/t/counterfeit-monkey-invisiclues/44257

But unfortunately, as you can see, the "spoiler" text is not captured.  Is it possible to replicate this behavior? 

Thank you, sincerely.

**Comment by gildas-lormeau** [comment]
It's hard to debug so I would say this is due to the fact that scripts on this page were not designed to be executed from an archive saved by SingleFile/SingleFileZ.

For this particular website, you could circumvent this issue by automatically unspoil the hidden text with a userscript just before capturing the page. For this, you must install an extension like GreaseMonkey and add the userscript below. You have also to enable the hidden option userScriptEnabled by exporting the settings from the options page of SingleFileZ, editing the JSON file, replacing `userScriptEnabled: false` with `userScriptEnabled: true`, and importing the modified file in SingleFileZ.

```
// ==UserScript==
// @name         [SingleFileZ] Unspoil text
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFileZ] Unspoil text
// @author       Gildas Lormeau
// @match        *://intfiction.org/*
// @noframes
// @grant        none
// ==/UserScript==

(() => {
  dispatchEvent(new CustomEvent("single-filez-user-script-init"));
  addEventListener("single-filez-on-before-capture-request", () => {
    document.querySelectorAll(".spoiled").forEach(spoilerElement => spoilerElement.click());
  });

})();
```

**Comment by boweden** [comment]
Thank you so much, as always. I will definitely do all those steps.

The reason I brought this up was because earlier, I was looking at a different html file with spoiler text:  http://mirror.ifarchive.org/if-archive/solutions/Aug4Solution.zip

In that case, I didn't have to install extensions like GreaseMonkey or add userscripts.  The spoilers worked fine.  So I thought this intfiction.org site was just an edge case.  But as you now explained, this situation seems much more complex.

Anyway, thank you, again.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I think a solution based on userscripts is the best I can propose. Feel free to comment or reopen it if necessary.
