### ISSUE TITLE
Request: Option to only save page once

### ISSUE THREAD

**Issue by GeorgeHahn** [gildas-lormeau/SingleFileZ#49]
It's easy to end up with many duplicates of the same page. This can get especially bad with many tabs open or when using an extension like [Workona](workona.com/).

Do you think there is a straightforward solution to this?

One option could be a new `file name conflict resolution` setting: `skip duplicates`. With that set, a file name template using the page URL or title and no time would not save duplicate pages.

PS: Thank you for the wonderful extension! I really appreciate all of the effort that has gone into this project.

**Comment by gildas-lormeau** [comment]
Changing the filename template in the options to `{page-title}.html` could fix this issue. However, instead of being skipped, the file would be rewritten.

**Comment by GeorgeHahn** [comment]
Totally! My other hope is that skipping the download would avoid some CPU & battery usage. I'd be happy to contribute this if you're open to it.

**Comment by gildas-lormeau** [comment]
I added the option "skip duplicate files". Note that it won't prevent SingleFile to process the page because the test is based on filenames and they may depend on the content of the processed page. However, it will prevent SingleFileZ to compress the assets so it will help to save some CPU. The feature will be available in the next version which should be available very soon.

**Comment by gildas-lormeau** [comment]
I just uploaded the version 0.5.52 which implements this feature. If you're using Firefox, it's available for download. It will be available on Chrome in a few days, after it has been reviewed by Google.
