### ISSUE TITLE
Autosave doesn't work with "nothing to repeat" displayed in the console

### ISSUE THREAD

**Issue by TheFrenchGhosty** [gildas-lormeau/SingleFileZ#52]
On one of my device, "autosave all tabs" is broken and will not save anything, a manual save will work without any issue.

When checking the Pending saves the page do appear in it, then disappear after some time.

When checking the console of the add-on (in about:debugging), "nothing to repeat" is displayed.

Screenshot (this is 4 different pages, that don't already exist, including https://github.com/gildas-lormeau/SingleFileZ / https://github.com/gildas-lormeau/SingleFileZ/issues and https://github.com/gildas-lormeau/SingleFileZ/issues/new):

![singlefilez](https://user-images.githubusercontent.com/47571719/83361789-7e179100-a37b-11ea-82f9-e88985c64c26.png)

According to the timestamp of the console, this is displayed when the warning appear:

![singlefilez2](https://user-images.githubusercontent.com/47571719/83361879-3e9d7480-a37c-11ea-80b9-6780d5025404.png)

Link of this ^ warning:

https://developer.mozilla.org/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookieBlockedForeign

Config:

https://github.com/TheFrenchGhosty/Firefox-Acceptable-Privacy/blob/master/Configurations/SingleFileZ/singlefilez-settings.json

Browser: Firefox 76.0.1

**Comment by gildas-lormeau** [comment]
Unfortunately this error does not come from the extension. There are 2 things you might check:
 - create a new profile and do a test with this new profile. In the past, it was possible to corrupt it because of this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1536796
 - set a smaller value for the option File name > max. length

I'm surprised the URL disappear from the pending queue though.

If this does not help, go to about:debugging#/runtime/this-firefox, find "SingleFileZ" in the list and click on the corresponding "Inspect" button. A new window containing the logs of the background page of the extension will be displayed. Click on the "console" tab and paste the errors you see.

**Comment by TheFrenchGhosty** [comment]
@gildas-lormeau I did more testing (sorry I didn't do it before) without any of my browser add-ons and found the issue: every time I set "file name conflict resolution" to "skip duplicate files" SingleFileZ will never Auto-save pages, setting it to any other option will make it work.

It's weird because it actually worked before... I think?

**Comment by gildas-lormeau** [comment]
Thank you so much @TheFrenchGhosty for the additional details. It was able to reproduce the issue and fix it in the version 0.5.59 I just published.

**Comment by TheFrenchGhosty** [comment]
Amazing! Thank you!
