### ISSUE TITLE
Empty page after saving

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#57]
Firefox 70.01 x32 (no any add-ons except the SFZ)
Windows 10 x64 LTSB 1607
SFZ  0.5.66

Here's the problem page:  https://www.forumhouse.ru/threads/225141/

The process of saving the page was successful, but the saved page appears blank.

My settings file:

[singlefilez-settings.zip](https://github.com/gildas-lormeau/SingleFileZ/files/5053852/singlefilez-settings.zip)

CentBrowser + SingleFileZ = no problem.  --> upd - sorry - CentBrowser have the same problem

Why so?

**Comment by gildas-lormeau** [comment]
I need to install Firefox 70.01 x32 to reproduce the issue I guess. Out of curiosity, what happens when you open the pages saved with CentBrowser in Firefox?

**Comment by kramola-RU** [comment]
> I need to install Firefox 70.01 x32 to reproduce the issue
wait wait wait ... :)
At first I want to check @ 80.0 beta 6


> what happens when you open the page saved with CentBrowser in Firefox?
This page displays correctly (it looks the same as in the CentBrowser).

**Comment by kramola-RU** [comment]
Firefox 80.0 beta 6 -- the same issue.
To reproduce the issue you must **log in** to the forum.

CentBrowser have the same problem (after login).

**Comment by gildas-lormeau** [comment]
The issue is fixed in the version 0.5.69 I just published. It was due to an invalid URL present in the CSS which was not handled properly by the script that auto-extracts the save page. For the record, the invalid URL is present in this rule in the CSS file.

`-xenforo-nomatch-background: #7e90ae url('-webkit-linear-gradient(bottom,rgba(255,255,255,0.2),rgba(255,255,255,0))')
}`

**Comment by kramola-RU** [comment]
Thank you very much !

**Comment by gildas-lormeau** [comment]
You're welcome :)
