### ISSUE TITLE
Docker Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by bydioeds** [gildas-lormeau/SingleFileZ#79]
Hello i'm trying to use this command 

`docker run --net=container:vpn singlefilez --crawl-links=true --crawl-inner-links-only=true --crawl-max-depth=1 "https://wikipedia.org" > file.html`

 and i get this error 

`Cannot read property 'map' of undefined`

it works fine with singlefile

**Comment by gildas-lormeau** [comment]
Hi,

I pushed a bunch of minor fixes and I may inadvertently have fixed this issue. On my end, I cannot reproduce it.

Note that if you want to save multiple pages with only one call to `singlefilez` (e.g. when crawling a site), then you have to mount as a volume the "/out" directory of the container. Also, you don't need to redirect the result into `file.html` (since multiple files will be generated) but you need to pass the option `--dump-content=false` (you should not need to pass it, it's a bug). Finally, crawling `https://wikipedia.org` is unfortunately a poor example because all the links on this page point to a different (sub) domain name. Here is an example that should work (on Linux/macOS etc.):
```
docker run -v $(pwd):/out singlefilez --crawl-links=true --crawl-inner-links-only=true --crawl-max-depth=1  --dump-content=false https://en.wikipedia.org/
```

**Comment by bydioeds** [comment]
> Edit: I guess this commit [60d70a6](https://github.com/gildas-lormeau/SingleFileZ/commit/60d70a631643c0591bb888233bfaffc66883a9fa) fixed the issue
Yes, now it works perfectly, many thanks.

**Comment by gildas-lormeau** [comment]
You're welcome
